#+title: FIN 420 Syllabus
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
#+options: toc:nil

#+BEGIN_CENTER
SUNY POLYTECHNIC INSTITUTE

SCHOOL OF BUSINESS ADMINISTRATION
#+END_CENTER


**Instructor**: Matthew Brigida, Ph.D.

**Office**: Donovan 1277

**Office Hours**: Tuesday and Wednesday, 4:30--6:00pm

**Email**:  matthew.brigida@sunyit.edu

**Class Location**:  Donovan 1157

**Class Day/Time**: MWF @ 8am

**Text**: Instructor Provided Materials

**Supplementary Material**: [[https://www.5minutefinance.org/][5MinuteFinance.org]]

* Course Structure and Interaction

The goal of the course is to understand the principles of corporate financial planning and control, and to also be able to apply them in real-world cases.  Constructing a financial plan requires a good knowledge of concepts/terms/measures learned in earlier courses.  To help you remember this material, I may reference materials I provide via the following media:  

-  Via BlackBaord Collaborate.  You can view them live (I'll let you know when I am recording), or under the `Recordings` section of Collaborate.

-  Short videos many of which are/will be posted on my YouTube channel: https://www.youtube.com/channel/UCwekb0vAK-FKaqPF5gfd0eQ/featured

* Description

In this course students will learn and apply the principles of corporate financial planning and control. The learning outcomes for this course are summarized below:

1. Students will use concepts learned in prior finance courses (such as how to analyze financial statements, perform time-value-of-money calculations, perform capital budgeting tasks, compute costs of capital, and manipulate corporate capital structure) in order to construct financial plans.
2.  Students will 'close-the-loop' by learning to measure the performance of financial plans, and then use this information to adjust the financial plan and projection.
3.  Students will learn to communicate complex topics in a clear and concise manner.
4.  Students will learn to calculate and present various measures of financial performance appropriate to specific types of firms.

* Academic Honesty Policy

Academic dishonesty will not be tolerated in this class. Cheating
on quizzes, examinations, and other forms of dishonesty (e.g., plagiarism, collusion, and
falsification of data) will be dealt with in a serious and formal manner. The penalty for academic
dishonesty in this class will be course failure. That is, any student who is found to be cheating
or engaged in other academically dishonest behavior will be failed for this course for this
semester. Course withdrawals to avoid such a failure will not be permitted. As a student, you
have a responsibility to become familiar with the Academic Honesty Policy found in the Student
Rights, Regulations, and Procedures Handbook.

* Participation

Your participation grade is a function of both your attendance, and your participation in the discussion while you are attending.  If you miss a few classes (particularly for a good reason) your grade won't be adversely affected, however if you *consistently* do not attend I will lower your participation score.  Similarly, if you *consistently* do not participate in the class discussion I will lower your score.  

* Course Communication

All communication will be through Blackboard and email. If you have question you are strongly encouraged to post it to a discussion forum instead of emailing me.  This way, other students can get the benefit of the question and answer.  It also saves me from answering the same question many times via email, and frees me up to answer more questions and generally provide more effective instruction for you.

* Grading


| Item                        | Points |
|-----------------------------+--------|
| Financial Plans and Reports |     70 |
| Participation               |     30 |
| Total Points                |    100 |
|-----------------------------+--------|


#+begin_center
**Final grades will be assigned according to the following scale**:
#+end_center

- 90 - 100 A
- 80 - 89.9 B
- 70 - 79.9 C
- 60 - 69.9 D
- $<$ 60 F

#+begin_quote
+/- grades may be assigned at the instructors discretion.
#+end_quote

* General Notes

- All times referred to in this course are Eastern Standard---unless otherwise indicated.
- There will be no make up exams or extra points assignments.
- Cheating will result in prosecution to the fullest extent possible under university rules.
- You are responsible for material covered in the online discussion, as well as text material.
-  **Internet Access:** This course requires that you have regular access to the internet to submit work.  You should not take this course if you plan on being in an area with insufficient internet access. "My internet was down for a week" is not an acceptable reason to hand in late work.
-  **Adding or Dropping the Course:** To add or drop the course the student should consult the university guidelines and withdrawal dates. The course instructor is not involved in a student's adding or withdrawing from the course.
- **Software:** You will need word processing and spreadsheet software to take
this course. Common examples of such software are Microsoft Word and
Excel. However, there is no need to buy this software if you don't already
have it. There are many free (open-source) alternatives which are just as
good (and which allow you to save/read files as .doc(x), .pdf, and .xls(x)).
Some widely used free office suites are LibreOffice (http://www.libreoffice.org)
and OpenOffice (http://www.openoffice.org). Feel free to download and use
these. *In this course all word processed submissions should be in .pdf, and
all spreadsheets should be submitted as .xlsx.*

* Some Notes on Spreadsheet Design

You should construct your spreadsheet as if you were an analyst at a company, and you were going to submit the spreadsheet to upper management.  Therefore, getting the correct answer can be considered the minimal amount of work.  The spreadsheet should be easily readable and organized.  There are a couple of reasons why this is important: (1) management often will check some numbers (or maybe change a few inputs if they have more up to date information) and it will reflect very poorly on you if they have to search around through a muddled and ill-conceived spreadsheet; and (2) anyone should be able to pick up your spreadsheet and complete it if you are not there (vacation, sick, or hopefully promoted).  Following are a couple tips on spreadsheet design, though it is far from exhaustive.

- Hard-code as little as possible.  You want a few cells for your inputs, or a place where you put your data, and then every other cell is linked and feeds off of these input cells. This way, to update your spreadsheet you simply change the inputs or drop in new data.  
- Take the time to label cells, and put in appropriate comments if necessary  - though comments should not be used excessively. Also, it is common to change the cell color depending on whether it is hard-coded (an input) or a formula.  This way you (or anyone else) can immediately look at a cell and tell whether it is one in which you can type (an input).  Don't forget to include a key.
- It is often better to add tabs to a spreadsheet than continue calculations on one tab.  You can easily page through spreadsheet tabs with `Ctrl+Shift' and `Page-up' or `Page-down'.
- Pivot tables.  While we probably won't need them in this course, you should nonetheless get to know them.  Pivot tables are incredibly useful for summarizing data, and it is very possible you will be asked in an interview whether you are familiar with them.  Similarly, get to know VLOOKUP.
-  If you are inputting a long formula, then break the calculation into multiple cells.  This makes it much easier to tell where a mistake was made - and everyone always spends a fair amount of time looking for errors.
- Excel has many built in formulas which can be useful, however it is important that you understand what the formula is doing to use them.  Blindly applying a formula can lead to trouble.  For example, if you use the IRR() function on cash flows with multiple roots, the formula will return the first root it finds without signaling to you that there are other roots.  Also, there are Excel formulas that are flat out incorrect - in particular the NPV() function.  So, use a function if it saves time, but first be sure you know what the function is doing and verify it works.  That said, in my experience it is better (and faster) to input your own formula instead of using Excel's.  You often have to break the calculation into a couple of steps, but this can be done quickly, and the result is a spreadsheet that you know works and is easily auditable.

* Some Discussion Papers on AI 

The following paper will not be important for this course, however you still may want to read them.

+ [[https://www.mckinsey.com/featured-insights/artificial-intelligence][McKinsey AI]]
+ [[https://www.mckinsey.com/~/media/McKinsey/Industries/Advanced%2520Electronics/Our%2520Insights/How%2520artificial%2520intelligence%2520can%2520deliver%2520real%2520value%2520to%2520companies/MGI-Artificial-Intelligence-Discussion-paper.ashx][AI: The Next Digital Frontier?]]
+ [[https://www.mckinsey.com/~/media/McKinsey/Featured%2520Insights/Artificial%2520Intelligence/Notes%2520from%2520the%2520AI%2520frontier%2520Applications%2520and%2520value%2520of%2520deep%2520learning/Notes-from-the-AI-frontier-Insights-from-hundreds-of-use-cases-Discussion-paper.ashx][Notes from the AI Frontier: Insights from Hundreds of Use Cases]]
+ [[https://www.mckinsey.com/~/media/McKinsey/Featured%2520Insights/Artificial%2520Intelligence/Notes%2520from%2520the%2520frontier%2520Modeling%2520the%2520impact%2520of%2520AI%2520on%2520the%2520world%2520economy/MGI-Notes-from-the-AI-frontier-Modeling-the-impact-of-AI-on-the-world-economy-September-2018.ashx][Notes from the AI Frontier: Modeling the Impact on the World Economy]]
+ [[https://www.mckinsey.com/~/media/McKinsey/Featured%2520Insights/Artificial%2520Intelligence/Applying%2520artificial%2520intelligence%2520for%2520social%2520good/MGI-Applying-AI-for-social-good-Discussion-paper-Dec-2018.ashx][Notes from the AI Frontier:  Applying AI for Social Good]]
